module.exports = {
    MODELS_COOK: "SERVER/MODELS/COOK",
    MODELS_ADMIN : "SERVER/MODELS/ADMIN",
    MODELS_CLIENT : "SERVER/MODELS/CLIENT",
    MODELS_OWNER : "SERVER/MODELS/OWNER",
    MODELS_WAITER : "SERVER/MODELS/WAITER",
    MODELS_REF_COOK : "Cook",
    MODELS_REF_ADMIN : "Admin",
    MODELS_REF_CLIENT : "Client",
    MODELS_REF_OWNER : "Owner",
    MODELS_REF_WAITER : "Waiter",
    MODELS_REF_RESTARAUNT : "Restaraunt",
    MODELS_REF_ORDER : "Order",
    MODELS_REF_DISH : "Dish",
    ORDER_STATUS_DONE : "ORDER/STATUS/DONE",
    ORDER_STATUS_IN_PROGRESS : "ORDER/STATUS/IN_PROGRESS"
}